version: '3'

services:

  mysql-development:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: viacep
    ports:
      - "3308:3306"
  
  admin:    
    image: adminer    
    ports:      
      - "8080:8080"