"""empty message

Revision ID: 09eb4bd23c0c
Revises: 16583b307700
Create Date: 2020-12-06 17:04:38.485138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09eb4bd23c0c'
down_revision = '16583b307700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Sellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Sellers_email'), 'Sellers', ['email'], unique=True)
    op.create_index(op.f('ix_Sellers_first_name'), 'Sellers', ['first_name'], unique=False)
    op.create_index(op.f('ix_Sellers_last_name'), 'Sellers', ['last_name'], unique=False)
    op.create_index(op.f('ix_Sellers_username'), 'Sellers', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Sellers_username'), table_name='Sellers')
    op.drop_index(op.f('ix_Sellers_last_name'), table_name='Sellers')
    op.drop_index(op.f('ix_Sellers_first_name'), table_name='Sellers')
    op.drop_index(op.f('ix_Sellers_email'), table_name='Sellers')
    op.drop_table('Sellers')
    # ### end Alembic commands ###
