"""empty message

Revision ID: 143c6aac43ae
Revises: 1f758f99da0e
Create Date: 2020-11-26 12:01:02.644648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '143c6aac43ae'
down_revision = '1f758f99da0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=60), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('volume_type', sa.String(length=10), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='w3_db'
    )
    op.create_index(op.f('ix_w3_db_Products_description'), 'Products', ['description'], unique=True, schema='w3_db')
    op.create_table('Sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=60), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='w3_db'
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='w3_db'
    )
    op.create_index(op.f('ix_w3_db_Users_first_name'), 'Users', ['first_name'], unique=False, schema='w3_db')
    op.create_index(op.f('ix_w3_db_Users_last_name'), 'Users', ['last_name'], unique=False, schema='w3_db')
    op.create_index(op.f('ix_w3_db_Users_username'), 'Users', ['username'], unique=True, schema='w3_db')
    op.create_table('products_sold',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['w3_db.Products.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['w3_db.Sales.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'sale_id')
    )
    op.create_table('Sellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['w3_db.Sales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='w3_db'
    )
    op.create_index(op.f('ix_w3_db_Sellers_first_name'), 'Sellers', ['first_name'], unique=False, schema='w3_db')
    op.create_index(op.f('ix_w3_db_Sellers_last_name'), 'Sellers', ['last_name'], unique=False, schema='w3_db')
    op.create_index(op.f('ix_w3_db_Sellers_username'), 'Sellers', ['username'], unique=True, schema='w3_db')
    op.create_table('Suppliers',
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('nick', sa.String(length=60), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['w3_db.Products.id'], ),
    sa.PrimaryKeyConstraint('cnpj'),
    schema='w3_db'
    )
    op.create_index(op.f('ix_w3_db_Suppliers_nick'), 'Suppliers', ['nick'], unique=True, schema='w3_db')
    op.create_index(op.f('ix_w3_db_Suppliers_phone'), 'Suppliers', ['phone'], unique=True, schema='w3_db')
    op.drop_index('ix_w3_db_Products_description', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_w3_db_Users_first_name', table_name='users')
    op.drop_index('ix_w3_db_Users_last_name', table_name='users')
    op.drop_index('ix_w3_db_Users_username', table_name='users')
    op.drop_table('users')
    op.drop_table('sales')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('created_on', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_on', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_on', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_on', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.CheckConstraint('`is_admin` in (0,1)', name='CONSTRAINT_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_w3_db_Users_username', 'users', ['username'], unique=True)
    op.create_index('ix_w3_db_Users_last_name', 'users', ['last_name'], unique=False)
    op.create_index('ix_w3_db_Users_first_name', 'users', ['first_name'], unique=False)
    op.create_table('products',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('value', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('volume_type', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('created_on', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_on', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_w3_db_Products_description', 'products', ['description'], unique=True)
    op.drop_index(op.f('ix_w3_db_Suppliers_phone'), table_name='Suppliers', schema='w3_db')
    op.drop_index(op.f('ix_w3_db_Suppliers_nick'), table_name='Suppliers', schema='w3_db')
    op.drop_table('Suppliers', schema='w3_db')
    op.drop_index(op.f('ix_w3_db_Sellers_username'), table_name='Sellers', schema='w3_db')
    op.drop_index(op.f('ix_w3_db_Sellers_last_name'), table_name='Sellers', schema='w3_db')
    op.drop_index(op.f('ix_w3_db_Sellers_first_name'), table_name='Sellers', schema='w3_db')
    op.drop_table('Sellers', schema='w3_db')
    op.drop_table('products_sold')
    op.drop_index(op.f('ix_w3_db_Users_username'), table_name='Users', schema='w3_db')
    op.drop_index(op.f('ix_w3_db_Users_last_name'), table_name='Users', schema='w3_db')
    op.drop_index(op.f('ix_w3_db_Users_first_name'), table_name='Users', schema='w3_db')
    op.drop_table('Users', schema='w3_db')
    op.drop_table('Sales', schema='w3_db')
    op.drop_index(op.f('ix_w3_db_Products_description'), table_name='Products', schema='w3_db')
    op.drop_table('Products', schema='w3_db')
    # ### end Alembic commands ###
