"""empty message

Revision ID: d17dce2e32bc
Revises: 
Create Date: 2020-12-08 17:47:26.897134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd17dce2e32bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Sellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Sellers_email'), 'Sellers', ['email'], unique=True)
    op.create_index(op.f('ix_Sellers_first_name'), 'Sellers', ['first_name'], unique=False)
    op.create_index(op.f('ix_Sellers_last_name'), 'Sellers', ['last_name'], unique=False)
    op.create_index(op.f('ix_Sellers_username'), 'Sellers', ['username'], unique=True)
    op.drop_index('ix_w3_db_Sellers_first_name', table_name='sellers')
    op.drop_index('ix_w3_db_Sellers_last_name', table_name='sellers')
    op.drop_index('ix_w3_db_Sellers_username', table_name='sellers')
    op.drop_table('sellers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellers',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_on', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_on', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.CheckConstraint('`is_admin` in (0,1)', name='CONSTRAINT_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_w3_db_Sellers_username', 'sellers', ['username'], unique=True)
    op.create_index('ix_w3_db_Sellers_last_name', 'sellers', ['last_name'], unique=False)
    op.create_index('ix_w3_db_Sellers_first_name', 'sellers', ['first_name'], unique=False)
    op.drop_index(op.f('ix_Sellers_username'), table_name='Sellers')
    op.drop_index(op.f('ix_Sellers_last_name'), table_name='Sellers')
    op.drop_index(op.f('ix_Sellers_first_name'), table_name='Sellers')
    op.drop_index(op.f('ix_Sellers_email'), table_name='Sellers')
    op.drop_table('Sellers')
    # ### end Alembic commands ###
